backend:
  name: github
  repo: mona-lisas

media_folder: static/assets
public_folder: /assets

collections:
  - name: item
    label: Item 
    folder: src/items
    create: true
    fields: 
      - { name: image, label: Image, widget: image, }
      - { name: title, label: Title, }
      - { name: author, label: Author, widget: author, }
      - { name: price, label: Price, widget: price, }
      # - { name: body, label: Post, widget: markdown, }